# Generated by Django 6.0.6 on 2026-06-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس کامل'),
        ),
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='کد پستی'),
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام گیرنده'),
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='تلفن گیرنده'),
        ),
    ]
